version: '3.8'

services:
 postgres:
  container_name: 'beadando-postgres'
  image: postgres:latest
  environment:
   - POSTGRES_PASSWORD=12345678
  ports:
   - 5432:5432
  volumes:
   - ./initdb:/docker-entrypoint-initdb.d:Z
  networks:
   - beadando-network

networks:
 beadando-network:
  name: 'beadando-network'
